/*
Copyright The XSTS-SH Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	appsv1 "github.com/xsts-sh/xstatefulset/api/apps/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// XStatefulSetLister helps list XStatefulSets.
// All objects returned here must be treated as read-only.
type XStatefulSetLister interface {
	// List lists all XStatefulSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1.XStatefulSet, err error)
	// XStatefulSets returns an object that can list and get XStatefulSets.
	XStatefulSets(namespace string) XStatefulSetNamespaceLister
	XStatefulSetListerExpansion
}

// xStatefulSetLister implements the XStatefulSetLister interface.
type xStatefulSetLister struct {
	listers.ResourceIndexer[*appsv1.XStatefulSet]
}

// NewXStatefulSetLister returns a new XStatefulSetLister.
func NewXStatefulSetLister(indexer cache.Indexer) XStatefulSetLister {
	return &xStatefulSetLister{listers.New[*appsv1.XStatefulSet](indexer, appsv1.Resource("xstatefulset"))}
}

// XStatefulSets returns an object that can list and get XStatefulSets.
func (s *xStatefulSetLister) XStatefulSets(namespace string) XStatefulSetNamespaceLister {
	return xStatefulSetNamespaceLister{listers.NewNamespaced[*appsv1.XStatefulSet](s.ResourceIndexer, namespace)}
}

// XStatefulSetNamespaceLister helps list and get XStatefulSets.
// All objects returned here must be treated as read-only.
type XStatefulSetNamespaceLister interface {
	// List lists all XStatefulSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1.XStatefulSet, err error)
	// Get retrieves the XStatefulSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appsv1.XStatefulSet, error)
	XStatefulSetNamespaceListerExpansion
}

// xStatefulSetNamespaceLister implements the XStatefulSetNamespaceLister
// interface.
type xStatefulSetNamespaceLister struct {
	listers.ResourceIndexer[*appsv1.XStatefulSet]
}
