/*
Copyright The XSTS-SH Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"
	fmt "fmt"

	appsv1 "github.com/xsts-sh/xstatefulset/api/apps/v1"
	applyconfigurationappsv1 "github.com/xsts-sh/xstatefulset/client-go/applyconfiguration/apps/v1"
	applyconfigurationautoscalingv1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"
	scheme "github.com/xsts-sh/xstatefulset/client-go/clientset/versioned/scheme"
	autoscalingv1 "k8s.io/api/autoscaling/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apply "k8s.io/client-go/util/apply"
)

// XStatefulSetsGetter has a method to return a XStatefulSetInterface.
// A group's client should implement this interface.
type XStatefulSetsGetter interface {
	XStatefulSets(namespace string) XStatefulSetInterface
}

// XStatefulSetInterface has methods to work with XStatefulSet resources.
type XStatefulSetInterface interface {
	Create(ctx context.Context, xStatefulSet *appsv1.XStatefulSet, opts metav1.CreateOptions) (*appsv1.XStatefulSet, error)
	Update(ctx context.Context, xStatefulSet *appsv1.XStatefulSet, opts metav1.UpdateOptions) (*appsv1.XStatefulSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, xStatefulSet *appsv1.XStatefulSet, opts metav1.UpdateOptions) (*appsv1.XStatefulSet, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*appsv1.XStatefulSet, error)
	List(ctx context.Context, opts metav1.ListOptions) (*appsv1.XStatefulSetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *appsv1.XStatefulSet, err error)
	Apply(ctx context.Context, xStatefulSet *applyconfigurationappsv1.XStatefulSetApplyConfiguration, opts metav1.ApplyOptions) (result *appsv1.XStatefulSet, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, xStatefulSet *applyconfigurationappsv1.XStatefulSetApplyConfiguration, opts metav1.ApplyOptions) (result *appsv1.XStatefulSet, err error)
	GetScale(ctx context.Context, xStatefulSetName string, options metav1.GetOptions) (*autoscalingv1.Scale, error)
	UpdateScale(ctx context.Context, xStatefulSetName string, scale *autoscalingv1.Scale, opts metav1.UpdateOptions) (*autoscalingv1.Scale, error)
	ApplyScale(ctx context.Context, xStatefulSetName string, scale *applyconfigurationautoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (*autoscalingv1.Scale, error)

	XStatefulSetExpansion
}

// xStatefulSets implements XStatefulSetInterface
type xStatefulSets struct {
	*gentype.ClientWithListAndApply[*appsv1.XStatefulSet, *appsv1.XStatefulSetList, *applyconfigurationappsv1.XStatefulSetApplyConfiguration]
}

// newXStatefulSets returns a XStatefulSets
func newXStatefulSets(c *AppsV1Client, namespace string) *xStatefulSets {
	return &xStatefulSets{
		gentype.NewClientWithListAndApply[*appsv1.XStatefulSet, *appsv1.XStatefulSetList, *applyconfigurationappsv1.XStatefulSetApplyConfiguration](
			"xstatefulsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *appsv1.XStatefulSet { return &appsv1.XStatefulSet{} },
			func() *appsv1.XStatefulSetList { return &appsv1.XStatefulSetList{} },
		),
	}
}

// GetScale takes name of the xStatefulSet, and returns the corresponding autoscalingv1.Scale object, and an error if there is any.
func (c *xStatefulSets) GetScale(ctx context.Context, xStatefulSetName string, options metav1.GetOptions) (result *autoscalingv1.Scale, err error) {
	result = &autoscalingv1.Scale{}
	err = c.GetClient().Get().
		Namespace(c.GetNamespace()).
		Resource("xstatefulsets").
		Name(xStatefulSetName).
		SubResource("scale").
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// UpdateScale takes the top resource name and the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *xStatefulSets) UpdateScale(ctx context.Context, xStatefulSetName string, scale *autoscalingv1.Scale, opts metav1.UpdateOptions) (result *autoscalingv1.Scale, err error) {
	result = &autoscalingv1.Scale{}
	err = c.GetClient().Put().
		Namespace(c.GetNamespace()).
		Resource("xstatefulsets").
		Name(xStatefulSetName).
		SubResource("scale").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scale).
		Do(ctx).
		Into(result)
	return
}

// ApplyScale takes top resource name and the apply declarative configuration for scale,
// applies it and returns the applied scale, and an error, if there is any.
func (c *xStatefulSets) ApplyScale(ctx context.Context, xStatefulSetName string, scale *applyconfigurationautoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (result *autoscalingv1.Scale, err error) {
	if scale == nil {
		return nil, fmt.Errorf("scale provided to ApplyScale must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	request, err := apply.NewRequest(c.GetClient(), scale)
	if err != nil {
		return nil, err
	}

	result = &autoscalingv1.Scale{}
	err = request.
		Namespace(c.GetNamespace()).
		Resource("xstatefulsets").
		Name(xStatefulSetName).
		SubResource("scale").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}
