/*
Copyright The XSTS-SH Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	appsv1 "k8s.io/client-go/applyconfigurations/apps/v1"
)

// XStatefulSetStatusApplyConfiguration represents a declarative configuration of the XStatefulSetStatus type for use
// with apply.
type XStatefulSetStatusApplyConfiguration struct {
	ObservedGeneration *int64                                          `json:"observedGeneration,omitempty"`
	Replicas           *int32                                          `json:"replicas,omitempty"`
	ReadyReplicas      *int32                                          `json:"readyReplicas,omitempty"`
	CurrentReplicas    *int32                                          `json:"currentReplicas,omitempty"`
	UpdatedReplicas    *int32                                          `json:"updatedReplicas,omitempty"`
	CurrentRevision    *string                                         `json:"currentRevision,omitempty"`
	UpdateRevision     *string                                         `json:"updateRevision,omitempty"`
	CollisionCount     *int32                                          `json:"collisionCount,omitempty"`
	Conditions         []appsv1.StatefulSetConditionApplyConfiguration `json:"conditions,omitempty"`
	AvailableReplicas  *int32                                          `json:"availableReplicas,omitempty"`
	Selector           *string                                         `json:"selector,omitempty"`
}

// XStatefulSetStatusApplyConfiguration constructs a declarative configuration of the XStatefulSetStatus type for use with
// apply.
func XStatefulSetStatus() *XStatefulSetStatusApplyConfiguration {
	return &XStatefulSetStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithObservedGeneration(value int64) *XStatefulSetStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithReplicas(value int32) *XStatefulSetStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithReadyReplicas(value int32) *XStatefulSetStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithCurrentReplicas sets the CurrentReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentReplicas field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithCurrentReplicas(value int32) *XStatefulSetStatusApplyConfiguration {
	b.CurrentReplicas = &value
	return b
}

// WithUpdatedReplicas sets the UpdatedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReplicas field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithUpdatedReplicas(value int32) *XStatefulSetStatusApplyConfiguration {
	b.UpdatedReplicas = &value
	return b
}

// WithCurrentRevision sets the CurrentRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentRevision field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithCurrentRevision(value string) *XStatefulSetStatusApplyConfiguration {
	b.CurrentRevision = &value
	return b
}

// WithUpdateRevision sets the UpdateRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateRevision field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithUpdateRevision(value string) *XStatefulSetStatusApplyConfiguration {
	b.UpdateRevision = &value
	return b
}

// WithCollisionCount sets the CollisionCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionCount field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithCollisionCount(value int32) *XStatefulSetStatusApplyConfiguration {
	b.CollisionCount = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *XStatefulSetStatusApplyConfiguration) WithConditions(values ...*appsv1.StatefulSetConditionApplyConfiguration) *XStatefulSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithAvailableReplicas sets the AvailableReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableReplicas field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithAvailableReplicas(value int32) *XStatefulSetStatusApplyConfiguration {
	b.AvailableReplicas = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *XStatefulSetStatusApplyConfiguration) WithSelector(value string) *XStatefulSetStatusApplyConfiguration {
	b.Selector = &value
	return b
}
