/*
Copyright The XSTS-SH Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"
	json "encoding/json"
	fmt "fmt"

	v1 "github.com/xsts-sh/xstatefulset/api/apps/v1"
	appsv1 "github.com/xsts-sh/xstatefulset/client-go/applyconfiguration/apps/v1"
	applyconfigurationautoscalingv1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"
	typedappsv1 "github.com/xsts-sh/xstatefulset/client-go/clientset/versioned/typed/apps/v1"
	autoscalingv1 "k8s.io/api/autoscaling/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
)

// fakeXStatefulSets implements XStatefulSetInterface
type fakeXStatefulSets struct {
	*gentype.FakeClientWithListAndApply[*v1.XStatefulSet, *v1.XStatefulSetList, *appsv1.XStatefulSetApplyConfiguration]
	Fake *FakeAppsV1
}

func newFakeXStatefulSets(fake *FakeAppsV1, namespace string) typedappsv1.XStatefulSetInterface {
	return &fakeXStatefulSets{
		gentype.NewFakeClientWithListAndApply[*v1.XStatefulSet, *v1.XStatefulSetList, *appsv1.XStatefulSetApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("xstatefulsets"),
			v1.SchemeGroupVersion.WithKind("XStatefulSet"),
			func() *v1.XStatefulSet { return &v1.XStatefulSet{} },
			func() *v1.XStatefulSetList { return &v1.XStatefulSetList{} },
			func(dst, src *v1.XStatefulSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1.XStatefulSetList) []*v1.XStatefulSet { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.XStatefulSetList, items []*v1.XStatefulSet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}

// GetScale takes name of the xStatefulSet, and returns the corresponding scale object, and an error if there is any.
func (c *fakeXStatefulSets) GetScale(ctx context.Context, xStatefulSetName string, options metav1.GetOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceActionWithOptions(c.Resource(), c.Namespace(), "scale", xStatefulSetName, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *fakeXStatefulSets) UpdateScale(ctx context.Context, xStatefulSetName string, scale *autoscalingv1.Scale, opts metav1.UpdateOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(c.Resource(), "scale", c.Namespace(), scale, opts), &autoscalingv1.Scale{})

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}

// ApplyScale takes top resource name and the apply declarative configuration for scale,
// applies it and returns the applied scale, and an error, if there is any.
func (c *fakeXStatefulSets) ApplyScale(ctx context.Context, xStatefulSetName string, scale *applyconfigurationautoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (result *autoscalingv1.Scale, err error) {
	if scale == nil {
		return nil, fmt.Errorf("scale provided to ApplyScale must not be nil")
	}
	data, err := json.Marshal(scale)
	if err != nil {
		return nil, err
	}
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(c.Resource(), c.Namespace(), xStatefulSetName, types.ApplyPatchType, data, opts.ToPatchOptions(), "scale"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}
