apiVersion: apps.x-k8s.io/v1
kind: XStatefulSet
metadata:
  name: test-xsts-minimal
  namespace: default
spec:
  # Only required fields - webhook will apply defaults
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: web
---
apiVersion: apps.x-k8s.io/v1
kind: XStatefulSet
metadata:
  name: test-xsts-with-pvc
  namespace: default
spec:
  selector:
    matchLabels:
      app: web
  serviceName: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: apps.x-k8s.io/v1
kind: XStatefulSet
metadata:
  name: test-xsts-custom
  namespace: default
spec:
  # Explicitly set some values - webhook will only apply missing defaults
  replicas: 3
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
          name: redis
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 1
